//define motors here (#define (name) (port))
#define MOTOR_DRIVE_FRONT_RIGHT 11
#define MOTOR_DRIVE_FRONT_LEFT 20
#define MOTOR_DRIVE_BACK_RIGHT 15
#define MOTOR_DRIVE_BACK_LEFT 18
#define MOTOR_ANGLER 10
#define MOTOR_LIFT 8
#define MOTOR_INTAKE_RIGHT 17
#define MOTOR_INTAKE_LEFT 14

/**

DUPLICATE COPY

#define MOTOR_DRIVE_FRONT_RIGHT 11
#define MOTOR_DRIVE_FRONT_LEFT 20
#define MOTOR_DRIVE_BACK_RIGHT 14
#define MOTOR_DRIVE_BACK_LEFT 18
#define MOTOR_ANGLER 10
#define MOTOR_LIFT 8
#define MOTOR_INTAKE_RIGHT 17
#define MOTOR_INTAKE_LEFT 13

*/
