#pragma config(Sensor, dgtl1,  drive_RightFront, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  drive_RightBack, sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  drive_LeftFront, sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  drive_LeftBack, sensorQuadEncoder)
#pragma config(Motor,  port2,           left_Front,    tmotorVex393HighSpeed_MC29, openLoop, encoderPort, dgtl5)
#pragma config(Motor,  port3,           right_Front,   tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, dgtl1)
#pragma config(Motor,  port4,           mogo_Left,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           left_Back,     tmotorVex393HighSpeed_MC29, openLoop, encoderPort, dgtl7)
#pragma config(Motor,  port6,           right_Back,    tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, dgtl3)
#pragma config(Motor,  port7,           mogo_Right,    tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//!!Code automatically generated by 'ROBOTC' configuration wizard               !!//

//---------------------------------------------------------------------------//
/*                                                                           /
/        Description: Competition template for VEX EDR                      /
/                                                                           /
/---------------------------------------------------------------------------*/
// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#define drivethreshhold 10
#define drivelimit 127
//---------------------------------------------------------------------------//
/*                          Pre-Autonomous Functions                         /
/                                                                           /
/  You may want to perform some actions before the competition starts.      /
/  Do them in the following function.  You must return from this function   /
/  or the autonomous and usercontrol tasks will not be started.  This       /
/  function is only called once after the cortex has been powered on and    /
/  not every time that the robot is disabled.                               /
/---------------------------------------------------------------------------/



/-----------------------------------------------------------------------------/
/                                                                             /
/  main task                                                                  /
/                                                                             /
/-----------------------------------------------------------------------------*/

void stack (int coneNumber){

}
void drive_Forward(int power) {
    motor[left_Front]= power;
    motor[left_Back] =power;
    motor[right_Front] =power;
    motor[right_Back] =power;
}

void turn_Left (int power) {
    motor[left_Front]= power;
    motor[Left_Back] =power;
    motor[Right_Front] =-power;
    motor[Right_Back] =-power;
}
void turn_Right (int power) {
    motor[left_Front]= -power;
    motor[left_Back] = -power;
    motor[right_Front] =power;
    motor[right_Back] =power;
}
void drive_Backward (int power) {
    motor[left_Front]= -power;
    motor[left_Back] = -power;
    motor[right_Front] = -power;
    motor[right_Back] = -power;
}

void mogo_In (int power) {
  motor[mogo_Left] =-power;
  motor[mogo_Right] =-power;

}
void mogo_Out (int power) {
    motor[mogo_Left] =-power;
  motor[mogo_Right] =-power;

}

void pre_auton()
{
// running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

    // Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
    // used by the competition include file, for example, you might want
    // to display your team name on the LCD in this function.
    // bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

//---------------------------------------------------------------------------//
/*                                                                           /
/                              Autonomous Task                              /
/                                                                           /
/  This task is used to control your robot during the autonomous phase of   /
/  a VEX Competition.                                                       /
/                                                                           /
/  You must modify the code to add your own robot specific commands here.   /
/---------------------------------------------------------------------------*/

task autonomous()
{
	SensorValue[drive_LeftBack] = 0;
	SensorValue[drive_RightBack] = 0;
	SensorValue[drive_LeftFront] = 0;
	SensorValue[drive_RightFront] = 0;
					//Cleared the sensor values
	while (((SensorValue[drive_LeftBack] +SensorValue[drive_LeftBack] +SensorValue[drive_LeftFront]+
					 SensorValue[drive_RightFront])/4) < 4320

{
	drive_Forward(127);
}


  AutonomousCodePlaceholderForTesting();
}

//---------------------------------------------------------------------------//
/*                                                                           /
/                              User Control Task                            /
/                                                                           /
/  This task is used to control your robot during the user control phase of /
/  a VEX Competition.                                                       /
/                                                                           /
/  You must modify the code to add your own robot specific commands here.   /
/---------------------------------------------------------------------------*/

task usercontrol()
{
    while (true){

    if(vexRt[Btn6D]){
        mogo_In(127);
}
    else if(vexRt[Btn6U]){
        mogo_Out(127);
}
		else if(vexRT[Btn5D]){
				mogo_In(100);
}
		else if(vexRT[Btn5U]){
				mogo_Out(60);
}
		else{
				mogo_In(0);
		}






    motor[right_Front] = motor[right_Back] = (abs(vexRT[Ch2])> drivethreshhold)?((vexRT[Ch2]>drivelimit)?drivelimit:((vexRT[Ch2]<(-drivelimit))?-drivelimit:vexRT[Ch2])):0;  //Driving Stuffs I need to figure out (is that a ternary inside of a ternary?)
    motor[left_Front] = motor[left_Back] = (abs(vexRT[Ch3])> drivethreshhold)?((vexRT[Ch3]>drivelimit)?drivelimit:((vexRT[Ch3]<(-drivelimit))?-drivelimit:vexRT[Ch3])):0;




}
}
