#pragma config(Sensor, dgtl1,  liftLeft,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  liftRight,      sensorQuadEncoder)
#pragma config(Motor,  port1,           left_Front,    tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           arm_LeftDown,  tmotorVex393_MC29, PIDControl, encoderPort, dgtl1)
#pragma config(Motor,  port3,           left_Back,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           right_Front,   tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           arm_RightDown, tmotorVex393_MC29, PIDControl, encoderPort, dgtl3)
#pragma config(Motor,  port6,           right_Back,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           arm_LeftUp,    tmotorVex393_MC29, PIDControl, encoderPort, dgtl1)
#pragma config(Motor,  port9,           mobile_Goal,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          arm_RightUp,   tmotorVex393_HBridge, PIDControl, reversed, encoderPort, dgtl3)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#define drivethreshhold 10
#define drivelimit 90
/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

#define PID_SENSOR_INDEX    liftLeft
#define PID_SENSOR_SCALE    1
#define PID_MOTOR_INDEX     arm_LeftUp & arm_LeftDown
#define PID_MOTOR_SCALE     -1
#define PID_LIFT_MAX       127
#define PID_LIFT_MIN     (-127)
#define PID_INTEGRAL_LIMIT  50
float  pid_Kp = 2.0;
float  pid_Ki = 0.04;
float  pid_Kd = 0.0;
task pidController()
{
    float  pidSensorCurrentValue;

    float  pidError;
    float  pidLastError;
    float  pidIntegral;
    float  pidDerivative;
    float  pidLiftLeft;


    // If we are using an encoder then clear it
    if( SensorType[ PID_SENSOR_INDEX ] == sensorQuadEncoder )
        SensorValue[ PID_SENSOR_INDEX ] = 0;

    // Init the variables - thanks Glenn :)
    pidLastError  = 0;
    pidIntegral   = 0;

    while( true )
        {
        // Is PID control active ?
        if( pidRunning )
            {
            // Read the sensor value and scale
            pidSensorCurrentValue = SensorValue[ PID_SENSOR_INDEX ] * PID_SENSOR_SCALE;

            // calculate error
            pidError = pidSensorCurrentValue - pidRequestedValue;

            // integral - if Ki is not 0
            if( pid_Ki != 0 )
                {
                // If we are inside controlable window then integrate the error
                if( abs(pidError) < PID_INTEGRAL_LIMIT )
                    pidIntegral = pidIntegral + pidError;
                else
                    pidIntegral = 0;
                }
            else
                pidIntegral = 0;

            // calculate the derivative
            pidDerivative = pidError - pidLastError;
            pidLastError  = pidError;

            // calculate drive
            pidLiftLeft = (pid_Kp * pidError) + (pid_Ki * pidIntegral) + (pid_Kd * pidDerivative);

            // limit drive
            if( pidLiftLeft > PID_LIFT_MAX )
                pidLiftLeft = PID_LIFT_MAX;
            if( pidLiftLeft < PID_LIFT_MIN )
                pidLiftLeft = PID_LIFT_MIN;

            // send to motor
            motor[ PID_MOTOR_INDEX ] = pidLiftLeft * PID_MOTOR_SCALE;
            }
        else
            {
            // clear all
            pidError      = 0;
            pidLastError  = 0;
            pidIntegral   = 0;
            pidDerivative = 0;
            motor[ PID_MOTOR_INDEX ] = 0;
            }

        // Run at 50Hz
        wait1Msec( 25 );
        }
}

/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*  main task                                                                  */
/*                                                                             */
/*-----------------------------------------------------------------------------*/





void drive_Forward(int power) {
	motor[left_Front]= power;
	motor[left_Back] =power;
	motor[right_Front] =power;
	motor[right_Back] =power;
}

void turn_Left (int power) {
	motor[left_Front]= power;;
	motor[Left_Back] =power;
	motor[Right_Front] =-power;
	motor[Right_Back] =-power;
}
void turn_Right (int power) {
	motor[left_Front]= -power;
	motor[left_Back] = -power;
	motor[right_Front] =power;
	motor[right_Back] =power;
}
void drive_Backward (int power) {
	motor[left_Front]= -power;
	motor[left_Back] = -power;
	motor[right_Front] = -power;
	motor[right_Back] = -power;
}


void arm_Up (int power) {
	motor[arm_LeftUp] =power;
  motor[arm_LeftDown] =power;
  motor[arm_RightUp] =power;
  motor[arm_RightDown] =power;
}
void arm_Down (int power) {
	motor[arm_LeftUp] =-power;
  motor[arm_LeftDown] =-power;
  motor[arm_RightUp] =-power;
  motor[arm_RightDown] =-power;

}
void claw_Open (int power) {
	motor[claw] =power;
}
void claw_Close (int power) {
	motor[claw] =-power;

}
void mogo_Intake (int power) {
	motor[mobile_Goal] = power
}
void mogo_Release (int power) {
	motor[mobile_Goal] =-power
}

void pre_auton()
{

  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  if(vexRT[Btn5U]){ //  Lifting Setup (I needs to figure out this PID stuff)
			arm_Up(127);}
		else if(vexRT[Btn5D]){
			arm_Down(127);}
		else{
			arm_Up(0)}

	if(vexRT[Btn6U]) {   //Claw stuffs
		claw_Close(127);
 } else if(vexRT[Btn6D]) {
  	claw_Open(127);
	} else {
   claw_Close(0);
	}

	if(vexRt[Btn7U]) {  //Mogo stuffs
		mogo_Intake(127);
	}
  else if(vexRT[Btn7D]) {
  	mogo_Release(127);
	} else {
    mogo_Intake(0);
	}
	motor[right_Front] = motor[right_Back] = (abs(vexRT[Ch2])> drivethreshhold)?((vexRT[Ch2]>drivelimit)?drivelimit:((vexRT[Ch2]<(-drivelimit))?-drivelimit:vexRT[Ch2])):0;  //Driving Stuffs I need to figure out (is that a ternary inside of a ternary?)
	motor[left_Front] = motor[left_Back] = (abs(vexRT[Ch3])> drivethreshhold)?((vexRT[Ch3]>drivelimit)?drivelimit:((vexRT[Ch3]<(-drivelimit))?-drivelimit:vexRT[Ch3])):0;
    UserControlCodePlaceholderForTesting();
}
