#pragma config(Motor,  port1,           Left_Front,    tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           Left_Middle,   tmotorNone, openLoop)
#pragma config(Motor,  port3,           Left_Back,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           Right_Front,   tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Right_Middle,  tmotorNone, openLoop)
#pragma config(Motor,  port6,           Right_Back,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           Claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Arm_Left,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Mobile_Goal,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Arm_Right,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/
void Drive_Forward(int power) {
	motor[Left_Front]= power;
	motor[Left_Middle]= power;
	motor[Left_Back] =power;
	motor[Right_Front] =power;
	motor[Right_Middle] =power;
	motor[Right_Back] =power;
}

void Turn_Left (int power) {
	motor[Left_Front]= power;
	motor[Left_Middle]= power;
	motor[Left_Back] =power;
	motor[Right_Front] =-power;
	motor[Right_Middle] =-power;
	motor[Right_Back] =-power;
}
void Turn_Right (int power) {
	motor[Left_Front]= -power;
	motor[Left_Middle]= -power;
	motor[Left_Back] = -power;
	motor[Right_Front] =power;
	motor[Right_Middle] =power;
	motor[Right_Back] =power;
}
void Drive_Backward (int power) {
	motor[Left_Front]= -power;
	motor[Left_Middle]= -power;
	motor[Left_Back] = -power;
	motor[Right_Front] = -power;
	motor[Right_Middle] = -power;
	motor[Right_Back] = -power;
}


void Arm_Up (int power) {
	motor[Arm_Left] =power;
  motor[Arm_Right] =power;
}
void Arm_Down (int power) {
	motor[Arm_Left] =-power;
  motor[Arm_Right] =-power;

}
void Claw_Open (int power) {
	motor[Claw] =power;
}
void Claw_Close (int power) {
	motor[Claw] =-power;

}
void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................

    // Remove this function call once you have "real" code.
    UserControlCodePlaceholderForTesting();
  }
}
